### ISSUE TITLE
Empty role ?

### ISSUE THREAD

**Issue by laurent-kling** [andrewrothstein/ansible-vault-ssh-helper#1]
A dummy role ?

**Comment by andrewrothstein** [comment]
take a look in the meta/main.yml: https://github.com/andrewrothstein/ansible-vault-ssh-helper/blob/master/meta/main.yml

**Comment by laurent-kling** [comment]
OK, you install the binary but you don’t:
- set all parameters
- take care of CentOS security exception

Please check this:
https://learn.hashicorp.com/vault/secrets-management/sm-ssh-otp

Best regards

Laurent

Envoyé de mon iPhone

Le 13 mars 2020 à 20:25, Andrew Rothstein <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #1<https://github.com/andrewrothstein/ansible-vault-ssh-helper/issues/1>.

**Comment by andrewrothstein** [comment]
Indeed, this role only installs the executable. Happy to review a PR that includes configuration plays to do more of the full setup.

**Comment by laurent-kling** [comment]
OK, my role is published, please check it :
https://galaxy.ansible.com/laurent_kling/vault_otp

Le 17 mars 2020 à 21:00, Andrew Rothstein <notifications@github.com<mailto:notifications@github.com>> a écrit :



Indeed, this role only installs the executable. Happy to review a PR that includes configuration plays to do more of the full setup.
